"""Update UserApp table V2

Revision ID: 39109367194e
Revises: 5092b6b6d4f9
Create Date: 2023-03-02 18:08:05.844855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39109367194e'
down_revision = '5092b6b6d4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserApp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserApp',
    sa.Column('id_user', sa.INTEGER(), server_default=sa.text('nextval(\'"UserApp_id_user_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('assure_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('license_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_user', name='UserApp_pkey'),
    sa.UniqueConstraint('assure_number', name='UserApp_assure_number_key'),
    sa.UniqueConstraint('email', name='UserApp_email_key'),
    sa.UniqueConstraint('license_number', name='UserApp_license_number_key'),
    sa.UniqueConstraint('password', name='UserApp_password_key'),
    sa.UniqueConstraint('phone_number', name='UserApp_phone_number_key')
    )
    # ### end Alembic commands ###
